package com.allan.price_watch.scraper.site;

import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.util.regex.Pattern;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.springframework.stereotype.Component;

import com.allan.price_watch.common.exception.ScrapeFailedException;
import com.allan.price_watch.product.entity.Site;
import com.allan.price_watch.product.entity.StockStatus;
import com.allan.price_watch.scraper.ScrapeResult;
import com.allan.price_watch.scraper.Scraper;

/**
 * Selectors below are built from real HTML the user inspected on a live
 * H&M product page (2026-07), using {@code data-testid} attributes rather
 * than H&M's hashed CSS classes (e.g. {@code c4676a}) — those are
 * auto-generated by their CSS-in-JS build and will change on every H&M
 * deploy, {@code data-testid} attributes are the stable, intentionally-
 * kept-for-testing hooks and far less likely to silently break.
 *
 * <p><b>Two things in here are still guesses, not confirmed:</b>
 * <ul>
 *   <li>The fallback {@code [data-testid=price]} selector for non-sale
 *       products — only {@code red-price} (the sale-price styling) has
 *       been observed directly. If a product with no discount uses a
 *       different attribute entirely, this will need adjusting.</li>
 *   <li>Out-of-stock detection — inferred from the add-to-bag button's
 *       {@code aria-disabled} state, never actually observed against a
 *       real sold-out product page. H&M may show a "Notify Me" button, a
 *       size-selector-only state, or something else entirely instead.</li>
 * </ul>
 * Both should be verified against real pages (one on sale, one sold out)
 * before trusting this in production — see the note left in {@code
 * detectStockStatus}.
 */
@Component
public class HAndMScraper implements Scraper {

  private static final String USER_AGENT =
      "Mozilla/5.0 (compatible; PriceWatchBot/1.0; +https://github.com/allan/price-watch)";
  private static final Pattern NON_PRICE_CHARS = Pattern.compile("[^0-9.]");

  @Override
  public Site getSite() {
    return Site.HM;
  }

  @Override
  public boolean supports(URI url) {
    String host = url.getHost();
    return host != null && host.contains("hm.com");
  }

  @Override
  public ScrapeResult fetch(URI url) {
    Document doc = fetchDocument(url);

    Element priceEl = doc.selectFirst("[data-testid=red-price]");
    if (priceEl == null) {
      priceEl = doc.selectFirst("[data-testid=price]");
    }
    if (priceEl == null) {
      throw new ScrapeFailedException("Could not find a price element on " + url);
    }

    Element nameEl = doc.selectFirst("[data-testid=product-name]");
    String name = nameEl != null ? nameEl.text() : null;

    // TODO: no product-image selector confirmed yet — leaving this null
    // rather than guessing at a generic "first <img> on the page"
    // selector, which would just as likely grab a logo or unrelated
    // image and silently store the wrong thumbnail.
    String thumbnailUrl = null;

    BigDecimal price = parsePrice(priceEl.text());
    StockStatus stockStatus = detectStockStatus(doc);

    return new ScrapeResult(name, price, stockStatus, thumbnailUrl);
  }

  private Document fetchDocument(URI url) {
    try {
      return Jsoup.connect(url.toString())
          .userAgent(USER_AGENT)
          .timeout(10_000)
          .get();
    } catch (IOException e) {
      throw new ScrapeFailedException("Could not reach " + url + ": " + e.getMessage());
    }
  }

  /** "PHP 749" -> 749. Strips everything but digits/decimal point, so thousands separators don't break parsing. */
  private BigDecimal parsePrice(String rawPrice) {
    String digitsOnly = NON_PRICE_CHARS.matcher(rawPrice).replaceAll("");
    if (digitsOnly.isBlank()) {
      throw new ScrapeFailedException("Could not parse price from: " + rawPrice);
    }
    return new BigDecimal(digitsOnly);
  }

  private StockStatus detectStockStatus(Document doc) {
    Element addToBagButton = doc.selectFirst("[data-testid=pdp_add_to_cart_button]");
    if (addToBagButton == null) {
      return StockStatus.UNKNOWN;
    }
    boolean disabled = "true".equals(addToBagButton.attr("aria-disabled"));
    return disabled ? StockStatus.OUT_OF_STOCK : StockStatus.IN_STOCK;
  }
}