package com.allan.price_watch.auth;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.allan.price_watch.auth.dto.IssuedTokens;
import com.allan.price_watch.auth.dto.LoginRequest;
import com.allan.price_watch.auth.dto.RegisterRequest;
import com.allan.price_watch.auth.entity.RefreshToken;
import com.allan.price_watch.auth.entity.User;
import com.allan.price_watch.auth.repository.RefreshTokenRepository;
import com.allan.price_watch.auth.repository.UserRepository;
import com.allan.price_watch.common.exception.EmailAlreadyRegisteredException;
import com.allan.price_watch.common.exception.InvalidCredentialsException;
import com.allan.price_watch.common.exception.InvalidRefreshTokenException;
import com.allan.price_watch.security.JwtService;

/** Handles registration, login, refresh rotation, and logout. */
@Service
public class AuthService {

  private static final long REFRESH_TOKEN_TTL_DAYS = 7;

  private final UserRepository userRepository;
  private final RefreshTokenRepository refreshTokenRepository;
  private final PasswordEncoder passwordEncoder;
  private final JwtService jwtService;
  private final SecureRandom secureRandom = new SecureRandom();

  public AuthService(
      UserRepository userRepository,
      RefreshTokenRepository refreshTokenRepository,
      PasswordEncoder passwordEncoder,
      JwtService jwtService) {
    this.userRepository = userRepository;
    this.refreshTokenRepository = refreshTokenRepository;
    this.passwordEncoder = passwordEncoder;
    this.jwtService = jwtService;
  }

  /** Creates a new user and returns an access/refresh token pair. */
  @Transactional
  public IssuedTokens register(RegisterRequest request) {
    String email = request.email().toLowerCase();

    if (userRepository.existsByEmailIgnoreCase(email)) {
      throw new EmailAlreadyRegisteredException();
    }

    User user = User.builder()
        .email(email)
        .passwordHash(passwordEncoder.encode(request.password()))
        .build();

    try {
      // Flush so Postgres generates user.id before we mint a JWT subject.
      user = userRepository.saveAndFlush(user);
    } catch (DataIntegrityViolationException e) {
      // Concurrent register with the same email.
      throw new EmailAlreadyRegisteredException();
    }

    if (user.getId() == null) {
      throw new IllegalStateException("User id was not generated by the database after insert");
    }

    return issueTokenPair(user);
  }

  /** Authenticates credentials and returns a fresh token pair. */
  @Transactional
  public IssuedTokens login(LoginRequest request) {
    String email = request.email().toLowerCase();

    // Same error for bad email or password to avoid email enumeration.
    User user = userRepository.findByEmailIgnoreCase(email)
        .orElseThrow(InvalidCredentialsException::new);

    if (!passwordEncoder.matches(request.password(), user.getPasswordHash())) {
      throw new InvalidCredentialsException();
    }

    return issueTokenPair(user);
  }

  /** Rotates a valid refresh token into a new access/refresh pair. */
  @Transactional
  public IssuedTokens refresh(String rawRefreshToken) {
    if (rawRefreshToken == null || rawRefreshToken.isBlank()) {
      throw new InvalidRefreshTokenException();
    }

    // Lock the row so concurrent refresh cannot double-issue.
    RefreshToken existing = refreshTokenRepository
        .findByTokenHashForUpdate(hash(rawRefreshToken))
        .orElseThrow(InvalidRefreshTokenException::new);

    // Reused revoked token → revoke all sessions for this user.
    if (existing.getRevokedAt() != null) {
      refreshTokenRepository.revokeAllActiveForUser(existing.getUser().getId(), Instant.now());
      throw new InvalidRefreshTokenException();
    }

    if (!existing.getExpiresAt().isAfter(Instant.now())) {
      throw new InvalidRefreshTokenException();
    }

    existing.setRevokedAt(Instant.now());
    refreshTokenRepository.save(existing);

    return issueTokenPair(existing.getUser());
  }

  /** Revokes the caller's refresh token if it is still valid (idempotent). */
  @Transactional
  public void logout(UUID userId, String rawRefreshToken) {
    if (rawRefreshToken == null || rawRefreshToken.isBlank()) {
      return;
    }
    refreshTokenRepository.findByTokenHash(hash(rawRefreshToken))
        .filter(rt -> rt.getUser().getId().equals(userId))
        .ifPresent(rt -> {
          rt.setRevokedAt(Instant.now());
          refreshTokenRepository.save(rt);
        });
  }

  /** Mints a short-lived JWT access token plus a new opaque refresh token. */
  private IssuedTokens issueTokenPair(User user) {
    String accessToken = jwtService.generateAccessToken(user.getId(), user.getEmail());

    String rawRefreshToken = generateOpaqueToken();
    RefreshToken refreshToken = RefreshToken.builder()
        .user(user)
        .tokenHash(hash(rawRefreshToken))
        .expiresAt(Instant.now().plus(Duration.ofDays(REFRESH_TOKEN_TTL_DAYS)))
        .build();
    refreshTokenRepository.save(refreshToken);

    return new IssuedTokens(accessToken, rawRefreshToken, jwtService.getAccessTokenTtlSeconds());
  }

  /** Builds a high-entropy opaque refresh token (not a JWT). */
  private String generateOpaqueToken() {
    byte[] bytes = new byte[32];
    secureRandom.nextBytes(bytes);
    return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
  }

  /** Hashes a refresh token with SHA-256 before storage or lookup. */
  private String hash(String rawToken) {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      byte[] hashBytes = digest.digest(rawToken.getBytes(StandardCharsets.UTF_8));
      return Base64.getEncoder().encodeToString(hashBytes);
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException(e);
    }
  }
}
