package com.allan.price_watch.auth;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.allan.price_watch.auth.dto.IssuedTokens;
import com.allan.price_watch.auth.dto.LoginRequest;
import com.allan.price_watch.auth.dto.RegisterRequest;
import com.allan.price_watch.auth.entity.RefreshToken;
import com.allan.price_watch.auth.entity.User;
import com.allan.price_watch.auth.repository.RefreshTokenRepository;
import com.allan.price_watch.auth.repository.UserRepository;
import com.allan.price_watch.common.exception.EmailAlreadyRegisteredException;
import com.allan.price_watch.common.exception.InvalidCredentialsException;
import com.allan.price_watch.common.exception.InvalidRefreshTokenException;
import com.allan.price_watch.security.JwtService;

/**
 * Refresh tokens issued here are opaque random strings, not JWTs — see the
 * note on {@code RefreshToken}/{@code JwtService} for why. This class is
 * also where refresh token <b>rotation</b> happens: every successful
 * {@code /auth/refresh} call revokes the token it was given and issues a
 * brand new pair, rather than reusing the same refresh token until it
 * naturally expires.
 *
 * <p>Presenting a <em>already-revoked</em> refresh token triggers reuse
 * detection: every still-active refresh session for that user is revoked.
 * That way a stolen-and-already-rotated token cannot keep a parallel
 * session alive after the legitimate client rotated past it.
 *
 * <p>The raw refresh string is returned only so the controller can put it in
 * an HttpOnly cookie — it is not meant to be stored in browser JS.
 */
@Service
public class AuthService {

  private static final long REFRESH_TOKEN_TTL_DAYS = 7;

  private final UserRepository userRepository;
  private final RefreshTokenRepository refreshTokenRepository;
  private final PasswordEncoder passwordEncoder;
  private final JwtService jwtService;
  private final SecureRandom secureRandom = new SecureRandom();

  public AuthService(
      UserRepository userRepository,
      RefreshTokenRepository refreshTokenRepository,
      PasswordEncoder passwordEncoder,
      JwtService jwtService) {
    this.userRepository = userRepository;
    this.refreshTokenRepository = refreshTokenRepository;
    this.passwordEncoder = passwordEncoder;
    this.jwtService = jwtService;
  }

  @Transactional
  public IssuedTokens register(RegisterRequest request) {
    String email = request.email().toLowerCase();

    if (userRepository.existsByEmailIgnoreCase(email)) {
      throw new EmailAlreadyRegisteredException();
    }

    User user = User.builder()
        .email(email)
        .passwordHash(passwordEncoder.encode(request.password()))
        .build();

    try {
      // saveAndFlush so Postgres uuidv7() is written + reloaded into user.id
      // before we mint a JWT that needs the id as subject.
      user = userRepository.saveAndFlush(user);
    } catch (DataIntegrityViolationException e) {
      // Race: two concurrent registers with the same email.
      throw new EmailAlreadyRegisteredException();
    }

    if (user.getId() == null) {
      throw new IllegalStateException("User id was not generated by the database after insert");
    }

    return issueTokenPair(user);
  }

  @Transactional
  public IssuedTokens login(LoginRequest request) {
    String email = request.email().toLowerCase();

    // Same exception whether the email doesn't exist or the password is
    // wrong — telling those two apart in the response would let an
    // attacker enumerate registered emails one guess at a time.
    User user = userRepository.findByEmailIgnoreCase(email)
        .orElseThrow(InvalidCredentialsException::new);

    if (!passwordEncoder.matches(request.password(), user.getPasswordHash())) {
      throw new InvalidCredentialsException();
    }

    return issueTokenPair(user);
  }

  @Transactional
  public IssuedTokens refresh(String rawRefreshToken) {
    if (rawRefreshToken == null || rawRefreshToken.isBlank()) {
      throw new InvalidRefreshTokenException();
    }

    // Pessimistic lock: concurrent refresh with the same raw token must not
    // both pass "still valid" and both issue a new pair.
    RefreshToken existing = refreshTokenRepository
        .findByTokenHashForUpdate(hash(rawRefreshToken))
        .orElseThrow(InvalidRefreshTokenException::new);

    // Reuse of an already-rotated (or logout-revoked) token is a strong signal
    // the token was stolen and both the legitimate client and the thief are
    // racing. Kill every active refresh session for this user so neither side
    // can keep minting access tokens without logging in again.
    if (existing.getRevokedAt() != null) {
      refreshTokenRepository.revokeAllActiveForUser(existing.getUser().getId(), Instant.now());
      throw new InvalidRefreshTokenException();
    }

    if (!existing.getExpiresAt().isAfter(Instant.now())) {
      throw new InvalidRefreshTokenException();
    }

    existing.setRevokedAt(Instant.now());
    refreshTokenRepository.save(existing);

    return issueTokenPair(existing.getUser());
  }

  @Transactional
  public void logout(UUID userId, String rawRefreshToken) {
    if (rawRefreshToken == null || rawRefreshToken.isBlank()) {
      return;
    }
    // Scoped to the calling user, not just the token hash — stops one
    // user from revoking a token that happens to belong to someone else
    // (defense in depth; a correct client would never send another
    // user's token, but the check costs nothing to add).
    refreshTokenRepository.findByTokenHash(hash(rawRefreshToken))
        .filter(rt -> rt.getUser().getId().equals(userId))
        .ifPresent(rt -> {
          rt.setRevokedAt(Instant.now());
          refreshTokenRepository.save(rt);
        });
    // No exception if the token is already gone/invalid — logout is
    // idempotent from the client's point of view either way.
  }

  private IssuedTokens issueTokenPair(User user) {
    String accessToken = jwtService.generateAccessToken(user.getId(), user.getEmail());

    String rawRefreshToken = generateOpaqueToken();
    RefreshToken refreshToken = RefreshToken.builder()
        .user(user)
        .tokenHash(hash(rawRefreshToken))
        .expiresAt(Instant.now().plus(Duration.ofDays(REFRESH_TOKEN_TTL_DAYS)))
        .build();
    refreshTokenRepository.save(refreshToken);

    return new IssuedTokens(accessToken, rawRefreshToken, jwtService.getAccessTokenTtlSeconds());
  }

  /** 32 random bytes, URL-safe Base64 — not a JWT, not decodable as one. */
  private String generateOpaqueToken() {
    byte[] bytes = new byte[32];
    secureRandom.nextBytes(bytes);
    return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
  }

  /**
   * SHA-256, deliberately not bcrypt/Argon2 — refresh tokens are already
   * 256 bits of {@code SecureRandom} entropy, not user-chosen secrets, so
   * there's no brute-forceable keyspace to slow an attacker down against.
   * A fast cryptographic hash is the right tool here; an adaptive one
   * would just waste CPU on every refresh/logout call for no security
   * benefit.
   */
  private String hash(String rawToken) {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      byte[] hashBytes = digest.digest(rawToken.getBytes(StandardCharsets.UTF_8));
      return Base64.getEncoder().encodeToString(hashBytes);
    } catch (NoSuchAlgorithmException e) {
      // SHA-256 is guaranteed available on every JVM per the Java
      // Cryptography Architecture spec — this branch is unreachable.
      throw new IllegalStateException(e);
    }
  }
}
